/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("MaintNotificationObjectPageObjectPage journey");

        opaTest("Navigate to MaintNotificationObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheMaintNotificationListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheMaintNotificationListGenerated.onTable().iCheckRows();
            When.onTheMaintNotificationListGenerated.onTable().iPressRow(0);

            Then.onTheMaintNotificationObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Check header actions of the Object Page", function (Given, When, Then) {
            // Ensure the opened entity is not in Draft state before uncommenting
            // Then.onTheMaintNotificationObjectPageGenerated.onHeader().iCheckEdit({ visible: true });
            // When.onTheMaintNotificationObjectPageGenerated.onHeader().iPressEdit();
            Then.onTheMaintNotificationObjectPageGenerated.onHeader().iCheckAction("Notification Processing");
            When.onTheMaintNotificationObjectPageGenerated.onHeader().iExecuteAction("Notification Processing");
        });


        opaTest("Check the number of sections of the Object Page", function (_Given, _When, Then) {
            Then.onTheMaintNotificationObjectPageGenerated.iCheckNumberOfSections(4);
        });

        opaTest("Check the Header section of the Object Page", function (_Given, When, Then) {
            When.onTheMaintNotificationObjectPageGenerated.iPressSectionIconTabFilterButton("Header");
            Then.onTheMaintNotificationObjectPageGenerated.iCheckSection({ section: "Header" });
            Then.onTheMaintNotificationObjectPageGenerated.onForm({ section: "Header" }).iCheckField({ property: "PlantID" });
            Then.onTheMaintNotificationObjectPageGenerated.onForm({ section: "Header" }).iCheckField({ property: "EquipmentID" });
            Then.onTheMaintNotificationObjectPageGenerated.onForm({ section: "Header" }).iCheckField({ property: "DamageCodeID" });
            Then.onTheMaintNotificationObjectPageGenerated.onForm({ section: "Header" }).iCheckField({ property: "TechnicianID" });
            Then.onTheMaintNotificationObjectPageGenerated.onForm({ section: "Header" }).iCheckField({ property: "FuncLocId" });
            Then.onTheMaintNotificationObjectPageGenerated.onForm({ section: "Header" }).iCheckField({ property: "Priority" });
            Then.onTheMaintNotificationObjectPageGenerated.onForm({ section: "Header" }).iCheckField({ property: "Status" });
            Then.onTheMaintNotificationObjectPageGenerated.onForm({ section: "Header" }).iCheckField({ property: "Description" });
            Then.onTheMaintNotificationObjectPageGenerated.onForm({ section: "Header" }).iCheckField({ property: "SlaHours" });
        });

        opaTest("Check the TechnicianDetails section of the Object Page", function (_Given, When, Then) {
            When.onTheMaintNotificationObjectPageGenerated.iPressSectionIconTabFilterButton("TechnicianDetails");
            Then.onTheMaintNotificationObjectPageGenerated.iCheckSection({ section: "TechnicianDetails" });
            Then.onTheMaintNotificationObjectPageGenerated.onForm({ section: "TechnicianDetails" }).iCheckField({ property: "TechFirstName" });
            Then.onTheMaintNotificationObjectPageGenerated.onForm({ section: "TechnicianDetails" }).iCheckField({ property: "TechLastName" });
            Then.onTheMaintNotificationObjectPageGenerated.onForm({ section: "TechnicianDetails" }).iCheckField({ property: "TechEmail" });
            Then.onTheMaintNotificationObjectPageGenerated.onForm({ section: "TechnicianDetails" }).iCheckField({ property: "TechPhone" });
            Then.onTheMaintNotificationObjectPageGenerated.onForm({ section: "TechnicianDetails" }).iCheckField({ property: "TechAvailability" });
        });

        opaTest("Check the MaintItems section of the Object Page", function (_Given, When, Then) {
            When.onTheMaintNotificationObjectPageGenerated.iPressSectionIconTabFilterButton("MaintItems");
            Then.onTheMaintNotificationObjectPageGenerated.iCheckSection({ section: "MaintItems" });
            Then.onTheMaintNotificationObjectPageGenerated.onTable({ property: "_MaintItem" }).iCheckAction({ service: "com.sap.gateway.srvd.zui_maintnotification_o4.v0001", action: "markItemCompleted", unbound: false } /* , { enabled: true } */);
            // When.onTheMaintNotificationObjectPageGenerated.onTable({ property: "_MaintItem" }).iPressAction({ service: "com.sap.gateway.srvd.zui_maintnotification_o4.v0001", action: "markItemCompleted", unbound: false });
            Then.onTheMaintNotificationObjectPageGenerated.onTable({ property: "_MaintItem" }).iCheckAction({ service: "com.sap.gateway.srvd.zui_maintnotification_o4.v0001", action: "markItemCancelled", unbound: false } /* , { enabled: true } */);
            // When.onTheMaintNotificationObjectPageGenerated.onTable({ property: "_MaintItem" }).iPressAction({ service: "com.sap.gateway.srvd.zui_maintnotification_o4.v0001", action: "markItemCancelled", unbound: false });
            Then.onTheMaintNotificationObjectPageGenerated.onTable({ property: "_MaintItem" }).iCheckColumns(undefined, {"ItemNo":{"header":"Item Number"},"ItemStatusText":{"header":"ItemStatusText"},"ActivityCode":{"header":"Activity Code"},"SparePartId":{"header":"Spare Part"},"RequiredQty":{"header":"Required Quantity"},"ItemStatus":{"header":"Status"}});
        });

        opaTest("Check the Attachments section of the Object Page", function (_Given, When, Then) {
            When.onTheMaintNotificationObjectPageGenerated.iPressSectionIconTabFilterButton("Attachments");
            Then.onTheMaintNotificationObjectPageGenerated.iCheckSection({ section: "Attachments" });
            Then.onTheMaintNotificationObjectPageGenerated.onTable({ property: "_Attachment" }).iCheckColumns(undefined, {"FileName":{"header":"File Name"},"FileContent":{"header":"File"},"MimeType":{"header":"MIME Type"},"CreatedBy":{"header":"Uploaded By"},"CreatedAt":{"header":"Uploaded On"}});
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});