/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("MaintNotificationListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheMaintNotificationListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheMaintNotificationListGenerated.onFilterBar().iCheckFilterField({ property: "PlantID" });
            Then.onTheMaintNotificationListGenerated.onFilterBar().iCheckFilterField({ property: "TechnicianID" });
            Then.onTheMaintNotificationListGenerated.onFilterBar().iCheckFilterField({ property: "Status" });
            Then.onTheMaintNotificationListGenerated.onFilterBar().iCheckFilterField({ property: "Priority" });
            Then.onTheMaintNotificationListGenerated.onFilterBar().iCheckFilterField({ property: "CreatedAt" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheMaintNotificationListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheMaintNotificationListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheMaintNotificationListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onTheMaintNotificationListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onTheMaintNotificationListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheMaintNotificationListGenerated.onTable(defaultTableId).iCheckCreate({ visible: true });
            // When.onTheMaintNotificationListGenerated.onTable(defaultTableId).iPressCreate();
            // When.onTheMaintNotificationListGenerated.onTable(defaultTableId).iPressDelete();
            Then.onTheMaintNotificationListGenerated.onTable(defaultTableId).iCheckDelete({ visible: true });
            // When.onTheMaintNotificationListGenerated.onTable(defaultTableId).iPressAction("Change Priority");
            Then.onTheMaintNotificationListGenerated.onTable(defaultTableId).iCheckAction("Change Priority", { enabled: false });
            // When.onTheMaintNotificationListGenerated.onTable(defaultTableId).iPressAction("Reassign Technician");
            Then.onTheMaintNotificationListGenerated.onTable(defaultTableId).iCheckAction("Reassign Technician", { enabled: false });
            // When.onTheMaintNotificationListGenerated.onTable(defaultTableId).iPressAction("Create From Template");
            Then.onTheMaintNotificationListGenerated.onTable(defaultTableId).iCheckAction("Create From Template", { enabled: false });
            Then.onTheMaintNotificationListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"PlantID":{"header":"Plant"},"EquipmentID":{"header":"Equipment"},"DamageCodeID":{"header":"Damage Code"},"TechnicianID":{"header":"Technician"},"FuncLocId":{"header":"Functional location"},"Priority":{"header":"Priority"},"Status":{"header":"Status"},"SlaHours":{"header":"SLA Hours"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheMaintNotificationListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheMaintNotificationListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheMaintNotificationListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheMaintNotificationObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});